default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  
  # Important configs for cloud9, change password value
  # to what you entered in the previous psql step.
  template: template0
  host: localhost
  username: postgres
  password: larry33$
  
development:
  <<: *default
  database: saas-project-app_developmentt

test:
  <<: *default
  database: saas-project-app_test

production:
  database: saas-project-app_production
  adapter: postgresql
  username: postgres
  password: <%= ENV['SAAS-PROJECT-APP_DATABASE_PASSWORD'] %>
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000